### ISSUE TITLE
Add ability to set number of ingredient/recipe factories.

### ISSUE THREAD

**Issue by AmericanPatriot6f0** [factoriolab/factorio-lab#227]
With the current system, one is unable to set an ingredient/input factory number, but we are only allowed to set output. This is especially frustrating when using fluids, as one cannot set a number of buildings for fluids. I suggest that we be allowed to set the number of factories for intermediates and inputs, so that fluid ratios become more easily calculated.

**Comment by dcbroad3** [comment]
Thanks for the suggestion!

So, I expect the most simple example use case for this is you want to tell the calculator to use one refinery, and just output the maximum possible amount of petroleum gas with all the cracking recipes included. If I'm understanding you correctly, I can see the appeal in that. 

The issue is that it's a completely different type of calculation. Today you might say, "I want to output 100 petroleum gas / minute." The calculator understands that as "Generate 100 petroleum gas / minute, minimizing the use of oil, then water, then number of factories." The simplex algorithm then solves the linear program, minimizing the 'cost' which is the input oil, water, and the number of factories.

What you're describing adds a 'maximization' problem *on top of that*. So it's "Using this number of factories, maximize the output of petroleum gas, but also minimize the use of oil, water, and factories." Simplex can only solve one minimize/maximize problem, not two, so we need to think about it a different way (that I honestly haven't figured out yet). Maybe it's possible to combine the two constraints into one objective.

On top of that, the calculator doesn't even understand some of the basics of this problem. There's no way to say "use this number of factories," if you do that currently it just translates that directly into a number of items but in this case we don't know the number of items yet because we have to calculate it. There's also no way to specify what you're trying to maximize. For example, you might say "using 1 refinery, maximize output" but you have to somewhere specify what you want to maximize, since it could be petroleum gas but it could also be heavy or light oil. For this use case you could just specify "1 factory of petroleum gas", which the UI handles, but then (especially with mods) we don't necessarily know what factory you're referring to. For example, do you want to maximize around 1 chemical plant running light oil cracking, or 1 refinery? You would need to be able to somehow say "Using x of this specific factory (or, more likely, this recipe), maximize the output of this specific product."

All of this to say, I would love to do what you're asking but it *is* complicated. I'll keep this in the back of my mind and I'll probably explore options at some point, but would likely require a major refactor or a completely different type of calculation.

**Comment by AmericanPatriot6f0** [comment]
![Screenshot 2020-10-15 060835](https://user-images.githubusercontent.com/68972888/96131445-0a030300-0eae-11eb-9631-9bfbc54e4049.png)
Here is an example of what I was thinking of.

**Comment by AmericanPatriot6f0** [comment]
> ![Screenshot 2020-10-15 060835](https://user-images.githubusercontent.com/68972888/96131445-0a030300-0eae-11eb-9631-9bfbc54e4049.png)
> Here is an example of what I was thinking of.
> 
> I don't know why you wouldn't be able to just have the inverse of the graph to maximize it. Is that not feasible?

Maybe for the calculator you could frame the problem by making factories a recipe type with their inputs/outputs being ingredients. (outputs inverse).

**Comment by dcbroad3** [comment]
That's a really nice way to integrate the concept into the UI, but it doesn't really solve the issue of needing to declare what you want to maximize. So you have to pick petroleum gas in the products list to even get this far, then you come in and change the number of refineries to 1. What do we do with the products you'd defined earlier? At that point you don't really want 1 petroleum gas per second, you just want to maximize petroleum gas subject to a constraint on the number of refineries. I suppose you would wipe out the "1 items/second" and just show the petroleum gas in the products, and assume that's what you're trying to maximize? Once you do that, things could start to get pretty weird.

Maybe I don't understand you, but simply inversing the graph doesn't really work, because the issue is that you're no longer declaring a number of outputs at all. It might be possible to solve with simplex, but it'd definitely take some exploring.

**Comment by dcbroad3** [comment]
Related: https://github.com/KirkMcDonald/kirkmcdonald.github.io/issues/154

**Comment by IgNaCy07** [comment]
And what's currently this alghoritm trying to maximize/minimize? Sum of all ingredients' amounts?
