### ISSUE TITLE
Pass ingredient info into CSV file

### ISSUE THREAD

**Issue by IgNaCy07** [factoriolab/factorio-lab#281]
So I'm trying to make a Python script that can create a graph (using Graphviz) from the CSV file generated by Factorio Lab.
An issue is that there is NO description what items are the particular steps using.
Currently, to solve this, I have to import the recipe files from the Github repository.
It might work, but imo this isn't the good solution.
What can be done is to include which items are respective steps using/producing and in which quantities - that's I think 4 new columns in CSV file.

**Comment by dcbroad3** [comment]
Could you give me an example of what you would like the CSV to look like?
Would this be solved by exporting the actual recipe data being used for each step?
What four columns did you have in mind?

**Comment by IgNaCy07** [comment]
I'd like something like this:
...Ingredients, Amounts of ingredients, Products, Amounts of products, ... (maybe after Recipe field?)
where the values are the items used/produced in the actual step, not in the recipe
so for example 10 refineries with prodmods 3 running adv oil processing would have the fields like that:
'crude-oil,water','6600,3300','heavy-oil,light-oil-petroleum-gas','2145,3861,4719'

**Comment by dcbroad3** [comment]
This is a little tricky because while the inputs to a step are clearly listed in the expanded menu, the outputs are not, and neither of these things are included as columns. 
Does it make sense to separate these out into 4 columns, or should I just include the JSON representation of the inputs and outputs? That would look like two columns, one like '{ 'crude-oil': 100, 'water': 50 }' and another like { 'heavy-oil': 10, 'light-oil': 25, 'petroleum-gas': 55 }

**Comment by IgNaCy07** [comment]
Yeah, that makes sense. Also, this can be used to merge other columns too: instead of ...2, express-transport-belt, 0.675, cargo wagon, ...
it would be collapsed into '{'express-transport-belt':2, 'cargo-wagon':0.675}'

**Comment by IgNaCy07** [comment]
In fact, instead of CSV file, the app could return a JSON file, because JSON seems more flexible and these workarounds wouldn't be needed.
