### ISSUE TITLE
Indent ingredients only used for one product

### ISSUE THREAD

**Issue by NotRexButCaesar** [factoriolab/factorio-lab#333]
When designing a factory, items only used once are usually produced on site. When viewing the calculator, it is difficult to see what recipes are used only once (such as belts and inserters for logistic science packs).

If these items where 100% of output is used in one place were indented, it would be much more convenient for the user.
![mockup](https://user-images.githubusercontent.com/68972888/104773218-8fa28300-5729-11eb-861b-02e157a42f7e.png)

**Comment by dcbroad3** [comment]
@NotRexButCaesar, if you have a minute, verify for me whether this is what you're looking for. It's up in staging:

https://factoriolab.github.io/staging/list?p=mining-productivity*1000&s=**3&v=1
![image](https://user-images.githubusercontent.com/8430702/121256644-c618a000-c87a-11eb-85e5-e07e1e12b601.png)


Note that I plan to put this as a setting, but for now this is always on in the staging environment.

**Comment by NotRexButCaesar** [comment]
This is exactly what I was thinking of.  If I could change it, I would only let the levels be collapsible.

**Comment by dcbroad3** [comment]
Great to hear. I am thinking of moving the hierarchy to its own column, so that the expand/collapse icons can still be interacted with more easily (and since they don't actually expand/collapse the hierarchy itself). This also means that you could show/hide the hierarchy column without putting another setting into the settings menu itself. 

As far as the levels being collapsible, maybe for the future, but to be fair that _is_ effectively what ignoring a step does 😄
