### ISSUE TITLE
Improved DSP Support

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factorio-lab#345]
Suggestions from @shadowtheage [here](https://github.com/ShadowTheAge/factorio-lab/issues/2#issuecomment-769374687)

Adjustments:
* Update data.json to properly handle mining "veins"
* Hide columns "Wagons", "Beacons", and "Pollution"
* Consider disabling recipes that use resources not in starting solar system

Settings:
* Remove difficulty
* Consider doing something with fuel and power since there are no burner factories
* Pipe flow rate not currently relevant
* Remove inserter settings (maybe add custom handling later but these are functionally different in DSP)
* Mining productivity exists, but functions differently
* Research speed exist, but functions differently

Known Bugs:
* Some recipes are missing producers

**Comment by ShadowTheAge** [comment]
> Mining productivity exists, but functions differently
Well, my suggestion is just to rename "Mining productivity" to "Mining speed" because vein usage is not part of the calculated model

**Comment by ShadowTheAge** [comment]
One thing is missing is "mining speed" (former mining productivity)
Another small thing is display for veins instead of miners (I have added fake "vein" item that does not belong to any category so it is hidden, and that "vein" item has factory settings)

Alltogether now I think my fork is more or less redundant and I'm going to place a link directing to the main FactorioLab

**Comment by dcbroad3** [comment]
@ShadowTheAge FYI, you can also use a special link to factoriolab:
https://factoriolab.github.io/dsp
It just redirects to the link you used, but easier to remember.
