### ISSUE TITLE
flow with link value "belts" badly rendered

### ISSUE THREAD

**Issue by baryluk** [factoriolab/factorio-lab#458]
Example, with "percent", then switched to "belt"

![Screenshot at 2021-04-10 17-39-24](https://user-images.githubusercontent.com/110322/114279362-ca177580-9a23-11eb-95dc-5c10903a7bca.png)

![Screenshot at 2021-04-10 17-39-35](https://user-images.githubusercontent.com/110322/114279366-cdaafc80-9a23-11eb-889f-8827108b2a7f.png)

The first looks really nice, the one with "belt" looks wonky and probably wrong.

**Comment by dcbroad3** [comment]
Are you referring to the extra link segments around the copper cable node that appear to lead nowhere? I think that is just a bug in the d3-sankey package, I will try to link to it later.

**Comment by baryluk** [comment]
yes, mostly the copper weirdness.

**Comment by dcbroad3** [comment]
The issue is apparently not documented in the d3-sankey GitHub, but it is well described here: https://observablehq.com/@enjalot/weird-sankey-links with code for a workaround.
I originally used the workaround in this article, but switched back to the original library and tried to give the nodes extra padding because I had to introduce a second workaround to account for circular references in the sankey diagram, and that workaround was incompatible with the original workaround for this issue. 

Unfortunately, most of these problems arise from the fact that d3-sankey is apparently not being maintained. I think the only way to resolve the root problem would be for me (or someone) to fork it and start to work on fixing these issues.
