### ISSUE TITLE
factorio calculator uses wrong assembly machine for some intermediates in Krastorio 2

### ISSUE THREAD

**Issue by DRY411S** [factoriolab/factorio-lab#484]
**Describe the bug**
Please see title

**To Reproduce**

[This link](https://factoriolab.github.io/list?z=eJwtz01OAkEUhdHd9OAlJiAr4FXVrYLGRlS60UkHCJqoASKBGAff2o0.ozM-xxcbDmzU7.5I83-ffq02dfU87Mf9sZ9WJzMPeMQTnvEGX-At3uEr.IJ.4l-Ea8IHUcQJcUe6Ir2S3kjvpDMKKKKEhDIqaIKmqEYzdIMaNEe3aIHu0D16QEvUog6t0CPaogOZPCMvyS25owwoDWVPOXE2C2a1-dp-EpfRN3WbTIc_)

See how level 5 assembly mchine is used for iron gear wheels, copper wire, iron sticks,, and assembly machine 1 for everything else. I cannot change the assembling machine either.

**Expected behavior**
It should use assembly machine 1.

**Screenshots**
See iron gear wheels and iron sticks
![image](https://user-images.githubusercontent.com/19732374/119277175-ff63d580-bc15-11eb-8e82-2096e5034072.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64-bit
 - Browser Chrome
 - Version Version 90.0.4430.212 (Official Build) (64-bit)

**Additional context**
Could be opertator error, first time I have tried to use this calculator, first time I have played Krastorio 2.

**Comment by dcbroad3** [comment]
If you expand the step and open the recipes tab, you can see there are two recipes for those steps. The calculator is choosing the advanced one which is only allowed to use lvl 5 assemblers. You can disable that recipe (chosen because it is more efficient) to force it to use the other recipe.

**Comment by DRY411S** [comment]
OK that has fixed it thanks. But if I say that I want to use the level 1 assemblers, the calculator really shouldn't use the lvel 5 assemblers. And the visual feedback, where I cannot change the assembler (but can for other things) just makes it less intuitive.  Perhaps the UI needs to be improved.

**Comment by dcbroad3** [comment]
I

**Comment by DRY411S** [comment]
I'm learning Krastorio 2 at the same ime as learning to use this splendid calculator, so not the best placed to comment.

But intuitively, it seems to me that if I select a default assembler level X , then the calculator should not propose to use assembler X+n unless there is no possible alternative. If I want to use a higher level assembler and optional recipe, then I could do that using the button that allows me to change assembler level.

**Comment by dcbroad3** [comment]
If it's all the same to you, I'll treat this issue as a request to update the default disabled recipes, and disable the advanced recipes by default. 

Solving this the way you request is not possible without a large refactor. Since the advanced recipes are separate recipes, the calculator:
1) Determines what assembler to use for each recipe, based on your default recipes.
   - For the simple recipe, it decides to use assembler 1 since you prefer that one.
   - For the advanced recipe, it will use assembler 5, since that is the only option. 
2) Determines which recipes to use in the solution, using the assigned assemblers for recipes.

There is currently no step at which the calculator dynamically disables recipes depending on your factory settings, and that is what would be required to do what you ask. I'm not sure that is a feature I want to add, since it's highly possible it could sometimes disable recipes you don't want to be disabled, and it might be unclear why recipes were ignored.

**Comment by DRY411S** [comment]
Perfect thank you.
