### ISSUE TITLE
Title Bar links to different game calculators

### ISSUE THREAD

**Issue by msarchet** [factoriolab/factorio-lab#524]
It's difficult to switch between the Dyson Sphere Program and Factorio calculators without knowing the specific urls to enter. I tried deleting the portion of the URL to go back from the Dyson Sphere calculator to the Factorio one. I tried refreshing the page using ctrl+f5 to do a full refresh and still was stuck on the DSP calculator. I had to look at the url and change the s=dsp to s=factorio to get back, which I feel isn't obvious to non-technical users that aren't familar with url structure. It's possible that I missed something on the page but wasn't able to find anything on the Wiki to indicate how to change between calculators for the two games.

To resolve this issue it would be nice to have either specific navigation links to the calculator for each game as either two separate links, or as a drop down menu with the links inside of it.

**Comment by msarchet** [comment]
I'm happy to make a pull request for this sometime in the next few days.

**Comment by dcbroad3** [comment]
The normal way to switch is to use the "Base Set" selection menu in the settings panel. 

![image](https://user-images.githubusercontent.com/8430702/122767558-cb112280-d270-11eb-89e4-d79d22441e92.png)

I plan to add support for Satisfactory as a third game in the next version, and for that I plan to add a separate "Game" dropdown in the settings panel, since the "Base Set" list is currently mostly cluttered with mods of Factorio. 

I can treat this issue as a request to go ahead and add that as a separate menu dropdown (in preparation for supporting Satisfactory instead of at the same time). Do you think that would address your request? A drop-down menu, like a down-arrow next to the title bar perhaps, isn't a bad idea but wasn't anything I had planned.

FYI: s=factorio doesn't actually link to the factorio calculator, it's just an invalid URL so it switches back to the defaults which is Factorio. For DSP you can use https://factoriolab.github.io/dsp, but there is no equivalent for factorio, and you're right that there probably should be since https://factoriolab.github.io will just preserve your last choice which might still be DSP.

**Comment by msarchet** [comment]
Oh nice! I had no idea that that was even a thing. I think a game drop down would be a great fix for this.

I was coming at this from the end of I couldn't figure out how to swap the game, and I don't think I ever would have thought to look in that area.

I will take a look at the code and see if I can help you with implementing this feature.
