### ISSUE TITLE
Allow more math in input fields

### ISSUE THREAD

**Issue by Dimava** [factoriolab/factorio-lab#557]
Sometimes I try to input output count as more advanced value then just `1/2`, but it does not work.
Even just `1.1/2` does not work, what to tell about `2*2`

I would like input fields would work with more or less advanced math expressions, maybe using some math library

As an example, I think something like https://www.npmjs.com/package/math-expression-evaluator will do

You also can write evaluator yourself, but that's a bit more difficult then adding dependency; or use `eval`, which is unsafe.

**Comment by dcbroad3** [comment]
I think this is outside the scope of something I am likely to do in this calculator, but I'll give it some thought. 

For what it's worth, `1 1/2` should work, as should `3/2`. It expects if you use a decimal to get a simple float and not to combine fractions with decimals, but any `<int> <fraction>` should work. 

Unfortunately most expression evaluators won't work out of the box with this calculator because I use a [custom Rational implementation](https://github.com/factoriolab/factorio-lab/blob/main/src/app/models/rational.ts). So for example any library that uses the standard Javascript number implementation will lose some precision on any long or repeating decimals, where my number implementation keeps full fidelity of fractions.
