### ISSUE TITLE
yet another minutes <-> seconds toggle

### ISSUE THREAD

**Issue by Schnobs** [factoriolab/factorio-lab#562]
Depending on context, I prefer to think of stuff either in units/minute or units/second. No matter which I use to start the calculation, I end up dividing or multiplying part of the results by 60. It isn't that hard, really, but somedays I wish there was a shortcut.

**Comment by dcbroad3** [comment]
What did you have in mind? Maybe a tooltip on all the rates that gives a breakdown of per second, per minute, and per hour? I think it wouldn't work to mix the display rate since units aren't given for every individual rate number.

**Comment by Schnobs** [comment]
The way I use the calculator, it could be the default behavior of the "Units per X" switch. I usually start my calculations with units/minute, and when I toggle it later, it's because I want to know "how much is that per second". On second thought, that only makes sense if I entered units per time to begin with. Errm.

I frankly have no idea where to place the function in the UI, or how to name it. Seeing how I cannot properly describe it in whole sentences, it's not fair that I expect you to come with a good label.

Perhaps a checkbox next to the selector, "maintain rate when switching between time scales"? That will make no sense to anyone who first sees it, but should become obvious enough when you try it for the first time.

**Comment by dcbroad3** [comment]
To be honest, I'm still not sure I understand what this checkbox would actually do, myself. 
Ah, maybe I get it. Currently when you switch the display rate it actually changes the amount of products you are asking for. You want it to maintain the same actual rate of products, just change the time units. So if you say 1 item per second of iron plates, and switch to display per minute, you want it to display 60 items per minute, instead of 1 item per minute as it does today.
That makes a lot of sense if that's what you mean, and now that you have me thinking about it, the current behavior could honestly be considered a bug I think. This should be pretty easy to accomplish, and I think I would just make it the standard behavior, no checkbox. I don't think anyone really wants it to change the rate of output products when they change that setting.

**Comment by Schnobs** [comment]
Thanks! Yes, that's what I had in mind.
