### ISSUE TITLE
Ray Receivers should use power when making critical photons

### ISSUE THREAD

**Issue by Gazer75** [factoriolab/factorio-lab#600]
Title says it all. They have no power use currently, but should use 120MW without Graviton lense and double that with them used.

**Comment by dcbroad3** [comment]
There was some discussion early on that ray receivers consume power from the dyson sphere instead of the normal electric grid:
https://github.com/factoriolab/factorio-lab/issues/387#issuecomment-777570388
But, it was also discussed that by the time they are relevant that is not really the case any longer. 
The only tricky part of this is that there is currently no way for a recipe to override a factory's power consumption. I don't think it would be terribly difficult to add, but it hasn't come up before.

**Comment by Gazer75** [comment]
Maybe have a section at the power summary for Dyson sphere power requirements? Nice to know the total required anyway.
