### ISSUE TITLE
Dyson Sphere Program: Various number changes

### ISSUE THREAD

**Issue by Queen-Gambit** [factoriolab/factorio-lab#624]
**Describe the bug**
A few Dyson Sphere Program updates has seen changes to some of the stats on factories making some factoriolab numbers outdated. Here is a list of the ones I found ingame:

**Dyson Sphere Program Version number**
0.8.21.8562 as of this writing

[https://i.imgur.com/R7H7uB5.png](url)
Assembling machine Mk.II 
Energy Consumption: from 480kW to 540kW
Drain: from 15kW to 18.0kW

[https://i.imgur.com/c6dByFh.png](url)
EM-Rail Ejector
Energy Consumption: from 1.2MW to 1.8MW

[https://i.imgur.com/hRg13SJ.png](url)
Mining Machine
Factoriolab just shows crafting speed 1. Should we add these additional information? :
Gathering speed 51 per minute
Energy Consumption: 420kW
Drain: 24kW

[https://i.imgur.com/nnyTaMQ.png](url)
Water Pump
Factoriolab doesn't have gathering speed should we add it?
Gathering speed 85 per minute

[https://i.imgur.com/XEp31r5.png](url)
Wind Turbine
Factoriolab doesn't have this item listed under factory however all the other factories are in it. Should we add it?
Provides 300kW power
Drain: none

**Comment by dcbroad3** [comment]
> Assembling machine Mk.II

Fixing this one. 

> EM-Rail Ejector

Fixing this one, although I'm taking your word for it, both wikis say it's 1.2MW.

> Mining Machine

The reason this one doesn't include power consumption is the calculator only determines the amount of veins required to be tapped by mining machines, there's no direct way to calculate a number of mining machines from the number of veins since it can vary quite a bit. Hence power consumption is left out here. 

> Water Pump

There's no direct equivalent for "gathering speed" in factoriolab. It's determined by the recipe time and the factory crafting speed. It should come out to the correct numbers when it comes down to it, but let me know if it seems incorrect.
Note: It should be base 50/minute, but is affected by mining speed bonuses, hopefully that accounts for your value of 85. 

> Wind Turbine

Currently, factoriolab can't do anything with buildings that don't craft recipes. Static buildings that produce or consume power without running recipes are ignored. That might be changed later, but for now this is by design.
