### ISSUE TITLE
Not optimal solution for "Coal liquefaction" using productivity modules (vs. kirkmcdonald)

### ISSUE THREAD

**Issue by asheiduk** [factoriolab/factorio-lab#652]
Your calculator computes a worse solution for the following problem:

- Rocket fuel: 80/min
- Sulfur: 80/min
- Recipe: Use "Coal liquefaction" instead of "Advanced oil processing" (n.b.: hard to find THAT)
- Use "Productivity module 3" everywhere

[Link to kirkmcdonald solution](https://kirkmcdonald.github.io/calc.html#zip=dY5LCsMwDERv41UELdm0Bh/G2HIiIlupP4XevvmQNl0UaaF5QjPytlpzhaXuKlIyvZqNE8uKKsZisrgJK4SGrLO+XbrSOLS8zSqKb4zFjGifLxBicNm6idKg537vjmkY65/dmvNV56gDrrwIk98whCwRPo6/Rgt/NAzWVZJ0ut7/PfQb)
[Link to your solution](https://factoriolab.github.io/list?z=eJwrcM7QsjCId3EDkmqZOVqG8U4pWoZqRS4uWlpaZlqedZ7xTrlwZgFCEMEygTOdQSpNQEy1NEMtt3jneI94T7ViLS2n0jrnOmfHugC1MmMAzB4fFQ__)

Your solution required 736.7 coal/min, kirkmcdonald only 507.209 coal/min

Additional notes:
- After removing the productivity modules both tools show the same values.
- kirkmcdonald uses fewer  oil refineries but uses light oil cracking to produce some additional petroleum gas. Your tool uses more oil refineries to produce the required petroleum gas but also adds the less efficient "solid fuel by heavy oil" recipe.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version [e.g. 95]

**Comment by dcbroad3** [comment]
From your link to FactorioLab, it looks like you have disabled **Light oil cracking to petroleum gas**. Because of this, the calculator has to spin up more refineries to get the petroleum required for the sulfur. 
Link to FactorioLab with cracking enabled shows the same results as kirkmcdonald:
https://factoriolab.github.io/list?z=eJwrcM7QsjCId3EDkmqZOVqG8U4pWoZqRS4uWlpaZlqedZ7xTrlwZgFCEMEygTOdQSpNQEy1NEMtt3jneI94T7ViLS3nOmfHugC1MmMAbhkd4A__

**Comment by asheiduk** [comment]
Ah... I think that's been left there while trying to configure oil liquefaction. I've mentioned something about that, didn't I? ;-)

Thank you for your tool and sorry for the fuss :-)
