### ISSUE TITLE
Updated data generator for Factorio mods

### ISSUE THREAD

**Issue by dcbroad3** [factoriolab/factorio-lab#737]
Ideally a Factorio mod that can output the required data for FactorioLab. 
Main concern with this is that such a tool would not be able to generate the icons / sprite sheet. That would likely require a second step / tool that would also need to be built.

**Comment by Aidiakapi** [comment]
In the spirit of information sharing, I've previously (2018) implemented a proof of concept extraction tool. I used scenarios to extract both prototypes, and icons.
Source code: https://github.com/Aidiakapi/graphio_extractor
The tool still works without issue nowadays (tested on Windows).

The two main things you cannot do solely from `control.lua` afaik are:
- Extracting actual image data.
- Getting actual string data for localized strings.

So a standalone tool that processes the information was required. In case you're interested, below describes the strategy used to extract the information.

---

For prototypes, I create a scenario with `control.lua`, and then use `factorio.exe --scenario2map generated_scenario_name`.
In order to get localized names, you can rely on the `log` method, which can take the localized names, and actually writes them to the standard output stream, properly substituted. I'm relying on ASCII control characters to delineate strings.

For icons, it's a bit more complicated:
- Again, generate a scenario with the `control.lua` code.
- Have the user run that scenario, it has three manual steps:
  1. Set UI scale to 100%.
  2. In graphics settings, disable clouds.
  3. Click start.
- It then uses UI to render each icon on a white, and black background.
- Take a screenshot of said icon:
  ```lua
    game.take_screenshot({
      player = player,
      by_player = player,
      surface = player.surface,
      position = { 0, 0 },
      resolution = { 32, 32 },
      zoom = 1,
      path = frames[frame_index].path,
      show_gui = true,
      show_entity_info = false,
      anti_alias = false,
  })
  ```
- Combine these icons into a single transparent icon.
  ![ammonia dark](https://user-images.githubusercontent.com/1985013/168467806-0f91dfd4-a116-440e-ab01-6ee43d879192.png) + ![ammonia light](https://user-images.githubusercontent.com/1985013/168467812-5e8134c6-abf5-4eb6-9bb8-27b78f254c8c.png) => ![ammonia transparent](https://user-images.githubusercontent.com/1985013/168467820-6c4db0a6-8ab1-4b1a-a7a1-ffaaf9fb2282.png)

In practice, because you have to insert several frames of delay, this takes a few minutes. However, it can be sped up greatly by putting the icons in for example, a 4x4 grid, at which point it'd only take a few seconds.

The end result of my tool is a `.png` tileset, and `.json` metadata file, this is from a [Krastorio2](https://mods.factorio.com/mod/Krastorio2) save file ([LICENSE](https://github.com/raiguard/krastorio-2/blob/master/LICENSE)):
![game_icons](https://user-images.githubusercontent.com/1985013/168468503-202fe7e7-1cc6-4a47-b146-199efba6931e.png)

```json
{
  "tile_metadata": {
    "tile_size": [
      32,
      32
    ],
    "tile_count": 568,
    "image_size": [
      768,
      768
    ]
  },
  "items": [
    {
      "id": "superior-exoskeleton-equipment",
      "localised_name": "Superior exoskeleton",
      "icon": 389
    },
    {
      "id": "kr-singularity-beacon",
      "localised_name": "Singularity beacon",
      "icon": 237
    },
    {
      "id": "quartz",
      "localised_name": "Quartz",
      "icon": 328
    },
    ...
```

**Comment by dcbroad3** [comment]
@Aidiakapi thanks so much for commenting! It's funny, your approach to saving out icons is basically identical to what I had in mind, right down to saving two copies with black/white backgrounds to restore the transparency. I will definitely look into your repo the next chance I get!

**Comment by dcbroad3** [comment]
Note to verify with KiwiHawk that remaining Sea Block issues are resolved with the new data generator.

**Comment by dcbroad3** [comment]
Published here: https://github.com/factoriolab/factorio-lab-export
